# ─────────────────────────────────────
# Configuração global do BedWars
# ─────────────────────────────────────

# Idioma do plugin.
# O arquivo deve existir em: plugins/BedWars/lang/<idioma>.yml
lang: pt_BR

# Configurações das arenas
arena:
  limits:
    # Largura máxima da arena no eixo X (defina 0 para ilimitado)
    max-width: 1000
    # Altura máxima da arena no eixo Y (defina 0 para ilimitado)
    max-height: 384
    # Comprimento máximo da arena no eixo Z (defina 0 para ilimitado)
    max-length: 1000

# ===================================================================
# Sistema SlimeWorld (AdvancedSlimePaper)
# ===================================================================
slimeworld:
  enabled: true
  templates-folder: templates
  max-loaded-instances: 5
  unload-timeout: 10m

# ===================================================================
# Verificador de atualizações no GitHub
# ===================================================================
version-check:
  enabled: true
  github: "sebastianjnuwu/bedwars"

# ===================================================================
# Configurações de Edição
# ===================================================================
edit:
  # Altura do mundo de edição (deve ser 0 para void)
  edit-world-height: 0
  # Tamanho da plataforma inicial de vidro (lado do quadrado)
  edit-platform-size: 10
  # Material da plataforma inicial
  edit-platform-block: GLASS
