name: ${project.name}
version: ${project.version}
main: dev.sebastianjnuwu.bedwars.BedWarsPlugin
api-version: 1.21
authors: ${project.developers}
softdepend: [WorldEdit, FancyNpcs]
description: Plugin de sBedWars para Paper 1.21.4 usando SlimeWorld
website: https://github.com/sebastianjnuwu

commands:
  bw:
    aliases:
      - bedwars
    permission: bw.player

  spawn:
    aliases:
      - lobby

permissions:
  bw.admin:
    default: op

  bw.player:
    default: true